# Builds a Drupal 11-ready PHP interpreter for macOS.
# The built interpreter only supports the CLI SAPI and a hard-coded list
# of extensions needed for running Drupal and Composer.
# Forked from https://raw.githubusercontent.com/crazywhalecc/static-php-cli/refs/heads/main/.github/workflows/build-macos-aarch64.yml.
# See https://www.drupal.org/docs/getting-started/system-requirements/php-requirements#extensions
name: Build for macOS

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PHP_EXTENSIONS: bz2,ctype,curl,dom,filter,gd,iconv,mbstring,opcache,openssl,pcntl,pdo,pdo_sqlite,phar,posix,session,simplexml,sodium,sqlite3,tokenizer,xml,xmlwriter,yaml,zip,zlib
  PHP_VERSION: 8.4

jobs:
  build:
    name: Build for macOS
    strategy:
      matrix:
        os:
          - macos-13  # x86_64
          - macos-14  # arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Install missing packages need to build PHP.
      - run: brew install automake coreutils gzip

      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: pecl, composer
          extensions: curl, openssl, mbstring, tokenizer
          ini-values: memory_limit=-1

      # Cache Composer dependencies.
      - id: cache-composer
        name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - if: steps.cache-composer.outputs.cache-hit != 'true'
        name: Install Composer dependencies
        run: composer install

      - name: Generate cache key
        run: |
          ARCH=$(uname -m)
          echo "ARCH=${ARCH}" >> $GITHUB_ENV
          INPUT_HASH=$(echo "${{ runner.os }}-${{ env.PHP_VERSION }}-${{ env.PHP_EXTENSIONS }}-$ARCH" | sha256sum | awk '{print $1}')
          echo "INPUT_HASH=${INPUT_HASH}" >> $GITHUB_ENV

      # Cache downloaded source code for PHP's dependencies.
      - id: cache-download
        name: Cache PHP source code
        uses: actions/cache@v4
        with:
          path: downloads
          key: sources-${{ env.INPUT_HASH }}

      # Cache the Drupal-ready PHP interpreter.
      - id: cache-runtime
        name: Cache Drupal-ready PHP interpreter
        uses: actions/cache@v4
        with:
          path: buildroot/bin/php
          key: runtime-${{ env.INPUT_HASH }}

      # Cache the minimal PHP interpreter.
      - id: cache-micro
        name: Cache minimal PHP interpreter
        uses: actions/cache@v4
        with:
          path: buildroot/bin/micro.sfx
          key: micro-${{ runner.os }}-${{ env.ARCH }}

      # Fetch the source code for PHP's dependencies if they aren't already cached.
      - if: steps.cache-download.outputs.cache-hit != 'true'
        name: Download PHP source code
        run: ./vendor/bin/spc download --with-php=${{ env.PHP_VERSION }} --for-extensions=${{ env.PHP_EXTENSIONS }} --prefer-pre-built

      # Build the Drupal-ready PHP interpreter and copy it into `bin`.
      - if: steps.cache-runtime.outputs.cache-hit != 'true'
        name: Build Drupal-ready PHP interpreter
        run: |
          ./vendor/bin/spc build ${{ env.PHP_EXTENSIONS }} --build-cli
          cp ./buildroot/bin/php ./drupal-launcher/bin

      # Build the launcher's minimal PHP interpreter.
      - if: steps.cache-micro.outputs.cache-hit != 'true'
        name: Build minimal PHP interpreter
        run: |
          ./vendor/bin/spc build --build-micro phar

      # Package the launcher as a phar file with the minimal PHP interpreter.
      - name: Build standalone launcher
        run: |
          composer build:phar
          ./vendor/bin/spc micro:combine launcher.phar -O launcher

      - name: Assemble package
        run: |
          mkdir -p ./drupal-launcher/bin
          cp $(which composer) ./drupal-launcher/bin
          cp ./buildroot/bin/php ./drupal-launcher/bin
          mv launcher ./drupal-launcher

      # Upload the fully built launcher.
      - uses: actions/upload-artifact@v4
        with:
          name: launcher-${{ runner.os }}-${{ env.ARCH }}
          path: drupal-launcher
