name: Build for macOS

on:
  workflow_dispatch:

jobs:
  runtime-arm64:
    uses: ./.github/workflows/runtime-macos.yml
    with:
      runner: macos-14

  runtime-x86_64:
    uses: ./.github/workflows/runtime-macos.yml
    with:
      runner: macos-13

  build:
    name: Build for macOS
    runs-on: macos-14
    needs:
      - runtime-arm64
      - runtime-x86_64
    steps:
      - uses: actions/checkout@v4

      - name: Download PHP interpreter binaries for arm64
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ needs.runtime-arm64.outputs.run_id }}

      - name: Download PHP interpreter binaries for x86_64
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ needs.runtime-x86_64.outputs.run_id }}

      - name: "Set up Go"
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.4'

      - name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: composer

      - name: Build launcher
        env:
          GOOS: darwin
        run: |
          GOARCH=arm64 go build -o launcher-arm64 launcher.go
          GOARCH=amd64 go build -o launcher-x86_64 launcher.go
          lipo -create -output launcher launcher-arm64 launcher-x86_64

      - name: Gather binaries
        run: |
          mkdir bin
          lipo -create -output ./bin/php ./bin-arm64/php ./bin-x86_64/php
          chmod +x ./bin/php
          cp $(which composer) ./bin

      - uses: actions/upload-artifact@v4
        with:
          name: drupal-launcher
          path: |
            bin/
            launcher
