name: Build runtime for macOS

on:
  workflow_call:
    inputs:
      runner:
        required: true
        description: The runner to use (macos-13 for x86_64, or macos-14 for arm64).
        type: string
    outputs:
      run_id:
        description: The workflow run ID, for downloading artifacts.
        value: ${{ github.run_id }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PHP_EXTENSIONS: bz2,ctype,curl,dom,filter,gd,iconv,mbstring,opcache,openssl,pcntl,pdo,pdo_sqlite,phar,posix,session,simplexml,sodium,sqlite3,tokenizer,xml,xmlwriter,yaml,zip,zlib
  PHP_VERSION: 8.3

jobs:
  build:
    name: Build for macOS
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: crazywhalecc/static-php-cli
          ref: 2.4.3

      - name: Generate cache key
        run: |
          ARCH=$(uname -m)
          echo "ARCH=${ARCH}" >> $GITHUB_ENV
          CACHE_KEY=${{ runner.os }}-$ARCH-$PHP_VERSION--$(echo $PHP_EXTENSIONS | tr ',' '-')
          echo "CACHE_KEY=${CACHE_KEY}" >> $GITHUB_ENV

      # Cache the built binaries so we can skip the build steps if there is a cache hit.
      - id: cache
        name: Cache binaries
        uses: actions/cache@v4
        with:
          path: buildroot/bin
          key: binaries-${{ env.CACHE_KEY }}

      # Install missing packages need to build PHP.
      - if: steps.cache.outputs.cache-hit != 'true'
        run: brew install automake gzip

      - if: steps.cache.outputs.cache-hit != 'true'
        name: "Set up PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: latest
          tools: pecl, composer
          extensions: curl, openssl, mbstring, tokenizer
          ini-values: memory_limit=-1

      - if: steps.cache.outputs.cache-hit != 'true'
        name: Install Composer dependencies
        run: composer install

      # Fetch the source code for PHP's dependencies if they aren't already cached.
      - if: steps.cache.outputs.cache-hit != 'true'
        name: Download PHP source code
        run: ./bin/spc download --with-php=${{ env.PHP_VERSION }} --for-extensions=${{ env.PHP_EXTENSIONS }} --prefer-pre-built

      # Build the minimal and Drupal-ready PHP interpreters.
      - if: steps.cache.outputs.cache-hit != 'true'
        name: Build PHP interpreters
        run: |
          ./bin/spc build ${{ env.PHP_EXTENSIONS }} --build-cli
          ./bin/spc build --build-micro phar

      # Upload the built interpreters.
      - uses: actions/upload-artifact@v4
        with:
          name: bin-${{ env.ARCH }}
          path: buildroot/bin
